In [16]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from mlxtend.frequent_patterns import apriori, association_rules

In [17]:
housing = pd.read_csv(r"C:\Users\Administrator.DAI-PC2\Downloads\Shubham\Practical Machine Learning\ClassWork\Datasets\Housing.csv")
housing.head()

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no

In [18]:
price_int = [(0,50000),(50000,100000),(100000,150000),(150000,200000)]
bins_price = pd.IntervalIndex.from_tuples(price_int)
housing['price_slab'] = pd.cut(housing['price'],bins_price)

area_int = [(0,5000),(5000,10000),(10000,15000),(15000,20000)]
bins_area = pd.IntervalIndex.from_tuples(area_int)
housing['area_slab'] = pd.cut(housing['lotsize'],bins_area)

housing.drop(['price','lotsize'],axis=1,inplace=True)

housing = housing.astype(object)
housing_dum = pd.get_dummies(housing,prefix_sep='_')

In [19]:
housing_dum.head()

,bedrooms_1,bedrooms_2,bedrooms_3,bedrooms_4,bedrooms_5,bedrooms_6,bathrms_1,bathrms_2,bathrms_3,bathrms_4,...,prefarea_no,prefarea_yes,"price_slab_(0, 50000]","price_slab_(50000, 100000]","price_slab_(100000, 150000]","price_slab_(150000, 200000]","area_slab_(0, 5000]","area_slab_(5000, 10000]","area_slab_(10000, 15000]","area_slab_(15000, 20000]"
0,False,False,True,False,False,False,True,False,False,False,...,True,False,True,False,False,False,False,True,False,False
1,False,True,False,False,False,False,True,False,False,False,...,True,False,True,False,False,False,True,False,False,False
2,False,False,True,False,False,False,True,False,False,False,...,True,False,True,False,False,False,True,False,False,False
3,False,False,True,False,False,False,True,False,False,False,...,True,False,False,True,False,False,False,True,False,False
4,False,True,False,False,False,False,True,False,False,False,...,True,False,False,True,False,False,False,True,False,False

In [20]:
itemsets = apriori(housing_dum, min_support = 0.5,use_colnames=True)

rules = association_rules(itemsets, metric= 'confidence', min_threshold = 0.7)

rules[['antecedents','consequents','support','confidence','lift']]

,antecedents,consequents,support,confidence,lift
0,(bedrooms_3),(gashw_no),0.525641,0.953488,0.999241
1,(bathrms_1),(driveway_yes),0.624542,0.848259,0.987525
2,(driveway_yes),(bathrms_1),0.624542,0.727079,0.987525
3,(bathrms_1),(recroom_no),0.628205,0.853234,1.037563
4,(recroom_no),(bathrms_1),0.628205,0.763920,1.037563
...,...,...,...,...,...
129,"(gashw_no, driveway_yes, recroom_no)",(prefarea_no),0.505495,0.762431,0.995903
130,"(prefarea_no, driveway_yes, recroom_no)",(gashw_no),0.505495,0.951724,0.997392
131,"(prefarea_no, driveway_yes)","(gashw_no, recroom_no)",0.505495,0.804665,1.026512
132,"(prefarea_no, recroom_no)","(gashw_no, driveway_yes)",0.505495,0.770950,0.939595
133,"(driveway_yes, recroom_no)","(gashw_no, prefarea_no)",0.505495,0.728232,1.004078

In [21]:
rules.sort_values(by = 'lift', ascending=False).head(6)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
102,(fullbase_no),"(prefarea_no, recroom_no)",0.650183,0.655678,0.503663,0.774648,1.181446,0.077352,1.527930,0.439029
100,"(prefarea_no, recroom_no)",(fullbase_no),0.655678,0.650183,0.503663,0.768156,1.181446,0.077352,1.508849,0.446035
41,"(area_slab_(0, 5000])",(prefarea_no),0.567766,0.765568,0.500000,0.880645,1.150316,0.065337,1.964162,0.302322
98,(fullbase_no),"(gashw_no, recroom_no)",0.650183,0.783883,0.575092,0.884507,1.128366,0.065424,1.871259,0.325208
96,"(gashw_no, recroom_no)",(fullbase_no),0.783883,0.650183,0.575092,0.733645,1.128366,0.065424,1.313347,0.526395
21,(fullbase_no),(recroom_no),0.650183,0.822344,0.602564,0.926761,1.126974,0.067890,2.425683,0.322077

In [22]:
rules_df = rules.sort_values(by = ['lift','confidence'], ascending=False)
relv_rules = rules_df[rules_df['lift']>1]
relv_rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
102,(fullbase_no),"(prefarea_no, recroom_no)",0.650183,0.655678,0.503663,0.774648,1.181446,0.077352,1.527930,0.439029
100,"(prefarea_no, recroom_no)",(fullbase_no),0.655678,0.650183,0.503663,0.768156,1.181446,0.077352,1.508849,0.446035
41,"(area_slab_(0, 5000])",(prefarea_no),0.567766,0.765568,0.500000,0.880645,1.150316,0.065337,1.964162,0.302322
98,(fullbase_no),"(gashw_no, recroom_no)",0.650183,0.783883,0.575092,0.884507,1.128366,0.065424,1.871259,0.325208
96,"(gashw_no, recroom_no)",(fullbase_no),0.783883,0.650183,0.575092,0.733645,1.128366,0.065424,1.313347,0.526395
...,...,...,...,...,...,...,...,...,...,...
16,(driveway_yes),(gashw_no),0.858974,0.954212,0.820513,0.955224,1.001060,0.000869,1.022589,0.007508
15,(gashw_no),(driveway_yes),0.954212,0.858974,0.820513,0.859885,1.001060,0.000869,1.006498,0.023125
76,"(driveway_yes, recroom_no)",(gashw_no),0.694139,0.954212,0.663004,0.955145,1.000977,0.000647,1.020793,0.003193
30,(fullbase_no),(gashw_no),0.650183,0.954212,0.620879,0.954930,1.000752,0.000466,1.015911,0.002147
97,"(fullbase_no, recroom_no)",(gashw_no),0.602564,0.954212,0.575092,0.954407,1.000204,0.000117,1.004274,0.000514